# Generated by Django 4.2.15 on 2025-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('prenom_personne', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=12)),
                ('image_personne', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
